In [80]:
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import preprocessing
from sklearn import utils
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [81]:
btc_df_1 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_1/btcFeature.csv')
btc_df_2 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_2/btcFeature.csv')
btc_df_3 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_3/btcFeature.csv')
btc_df_4 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_4/btcFeature.csv')

In [82]:
shift = -3
random_state = 0
btc_df_1.Change = btc_df_1.Change.shift(shift)
btc_df_1 = btc_df_1.dropna()

btc_df_2.Change = btc_df_2.Change.shift(shift)
btc_df_2 = btc_df_2.dropna()

btc_df_3.Change = btc_df_3.Change.shift(shift)
btc_df_3 = btc_df_3.dropna()

btc_df_4.Change = btc_df_4.Change.shift(shift)
btc_df_4 = btc_df_4.dropna()

In [83]:
lm_1 = LinearRegression()

X_1 = btc_df_1[['Sentiment', 'Volume', 'NoOfTweets']]
Y_1 = btc_df_1['Change']

X_train_1, X_test_1, Y_train_1, Y_test_1 = train_test_split(X_1, Y_1, test_size=0.33, random_state=random_state)

model = sm.OLS(Y_1, X_1).fit()
predictions = model.predict(X_1) # make the predictions by the model
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 Change   R-squared:                       0.005
Model:                            OLS   Adj. R-squared:                  0.001
Method:                 Least Squares   F-statistic:                     1.305
Date:                Sat, 24 Mar 2018   Prob (F-statistic):              0.272
Time:                        12:09:48   Log-Likelihood:                -4860.3
No. Observations:                 847   AIC:                             9727.
Df Residuals:                     844   BIC:                             9741.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Sentiment    109.1537     60.010      1.819      0.069      -8.633     226.941
Volume      4.888e-05   4.45e-05      1.098      0.272   -3.85e-05       0.000
NoOfTweets    -0.0048      0.002     -1.938      0.053      -0.010    6.21e-05
==============================================================================
Omnibus:                      102.902   Durbin-Watson:                   2.259
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              670.521
Skew:                           0.312   Prob(JB):                    2.50e-146
Kurtosis:                       7.314   Cond. No.                     3.08e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.08e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [84]:
#lm = linear_model.LinearRegression()
model = lm_1.fit(X_1,Y_1)

In [85]:
predictions = lm_1.predict(X_1)
print(X_1[0:5])
print(predictions[0:5])

   Sentiment         Volume  NoOfTweets
0   0.129824  101879.724252        5467
1   0.164874  102390.922041        5126
2   0.179189  103844.936107        4988
3   0.164394  102671.806232        4938
4   0.147747  100960.453183        4657
[-6.29579094  0.46691267  3.31160603  0.86874346 -1.3530026 ]


In [86]:
lm_1.score(X_1,Y_1)

0.0060468467280835325

In [87]:
lm_1.intercept_

-21.653110115429296

In [88]:
lm_2 = LinearRegression()

X_2 = btc_df_2[['Sentiment', 'Volume', 'NoOfTweets']]
Y_2 = btc_df_2['Change']

X_train_2, X_test_2, Y_train_2, Y_test_2 = train_test_split(X_2, Y_2, test_size=0.33, random_state=random_state)

model_2 = sm.OLS(Y_2, X_2).fit()
predictions = model_2.predict(X_2) # make the predictions by the model
model_2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 Change   R-squared:                       0.002
Model:                            OLS   Adj. R-squared:                 -0.002
Method:                 Least Squares   F-statistic:                    0.5434
Date:                Sat, 24 Mar 2018   Prob (F-statistic):              0.653
Time:                        12:09:49   Log-Likelihood:                -4743.0
No. Observations:                 822   AIC:                             9492.
Df Residuals:                     819   BIC:                             9506.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Sentiment     66.0774     62.577      1.056      0.291     -56.753     188.908
Volume      3.858e-05    4.6e-05      0.839      0.402   -5.17e-05       0.000
NoOfTweets    -0.0032      0.003     -1.271      0.204      -0.008       0.002
==============================================================================
Omnibus:                      141.513   Durbin-Watson:                   2.093
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1307.451
Skew:                           0.470   Prob(JB):                    1.23e-284
Kurtosis:                       9.107   Cond. No.                     3.05e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.05e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [89]:
#lm = linear_model.LinearRegression()
model_2 = lm_2.fit(X_2,Y_2)

In [90]:
predictions = lm_2.predict(X_2)
print(X_2[0:5])
print(predictions[0:5])

   Sentiment         Volume  NoOfTweets
0   0.131372  101879.724252        5479
1   0.165591  102439.846847        5089
2   0.174403  103800.678995        5006
3   0.166817  102671.102925        4817
4   0.150134  101054.829766        4647
[-4.58819756 -0.22214587  0.93570454  0.38836564 -1.19174045]


In [91]:
lm_2.score(X_2,Y_2)

0.0025724765933763383

In [92]:
lm_2.intercept_

-14.572300798382296

In [93]:
lm_3 = LinearRegression()

X_3 = btc_df_3[['Sentiment', 'Volume', 'NoOfTweets']]
Y_3 = btc_df_3['Change']

X_train_3, X_test_3, Y_train_3, Y_test_3 = train_test_split(X_3, Y_3, test_size=0.33, random_state=random_state)

model_3 = sm.OLS(Y_3, X_3).fit()
predictions = model_3.predict(X_3) # make the predictions by the model
model_3.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 Change   R-squared:                       0.002
Model:                            OLS   Adj. R-squared:                 -0.002
Method:                 Least Squares   F-statistic:                    0.5523
Date:                Sat, 24 Mar 2018   Prob (F-statistic):              0.647
Time:                        12:09:49   Log-Likelihood:                -4761.1
No. Observations:                 824   AIC:                             9528.
Df Residuals:                     821   BIC:                             9542.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Sentiment     94.4791     76.266      1.239      0.216     -55.220     244.178
Volume      2.791e-05   4.69e-05      0.596      0.552   -6.41e-05       0.000
NoOfTweets    -0.0033      0.003     -1.237      0.217      -0.008       0.002
==============================================================================
Omnibus:                      134.781   Durbin-Watson:                   2.027
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1051.750
Skew:                           0.488   Prob(JB):                    4.12e-229
Kurtosis:                       8.448   Cond. No.                     3.69e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.69e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [94]:
#lm = linear_model.LinearRegression()
model = lm_3.fit(X_3,Y_3)

In [95]:
predictions = lm_3.predict(X_3)
print(X_3[0:5])
print(predictions[0:5])

   Sentiment         Volume  NoOfTweets
0   0.119320  101879.724252        5471
1   0.144728  102439.846847        5095
2   0.153438  103800.678995        5012
3   0.142586  102671.102925        4908
4   0.120732  101054.829766        4631
[-3.99146785 -0.58100896  0.44417504 -0.04758156 -0.77116753]


In [96]:
lm_3.score(X_3,Y_3)

0.0020467634282066438

In [97]:
lm_3.intercept_

4.6518851424558552

In [98]:
lm_4 = LinearRegression()

X_4 = btc_df_4[['Sentiment', 'Volume', 'NoOfTweets']]
Y_4 = btc_df_4['Change']

X_train_4, X_test_4, Y_train_4, Y_test_4 = train_test_split(X_4, Y_4, test_size=0.33, random_state=random_state)

model_4 = sm.OLS(Y_4, X_4).fit()
predictions = model_4.predict(X_4) # make the predictions by the model
model_4.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 Change   R-squared:                       0.008
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     2.137
Date:                Sat, 24 Mar 2018   Prob (F-statistic):             0.0941
Time:                        12:09:50   Log-Likelihood:                -4874.1
No. Observations:                 844   AIC:                             9754.
Df Residuals:                     841   BIC:                             9768.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Sentiment    146.9388     62.398      2.355      0.019      24.465     269.412
Volume      5.498e-05    4.6e-05      1.195      0.232   -3.53e-05       0.000
NoOfTweets    -0.0064      0.003     -2.494      0.013      -0.011      -0.001
==============================================================================
Omnibus:                       96.892   Durbin-Watson:                   2.159
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              604.906
Skew:                           0.285   Prob(JB):                    4.43e-132
Kurtosis:                       7.108   Cond. No.                     3.08e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.08e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [99]:
model_4 = lm_4.fit(X_4,Y_4)

In [100]:
predictions = lm_4.predict(X_4)
print(X_4[0:5])
print(predictions[0:5])

   Sentiment         Volume  NoOfTweets
0   0.135402  101879.724252        5458
1   0.166256  102439.846847        5155
2   0.174352  103800.678995        5024
3   0.163713  102671.102925        4914
4   0.146757  101054.829766        4527
[-8.6449248  -1.48230465  0.73492228 -0.73041379 -2.00031688]


In [101]:
lm_4.score(X_4,Y_4)

0.0079576905898477435

In [102]:
lm_4.intercept_

-12.972028009730673