In [27]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import preprocessing
from sklearn import utils
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_classification
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.model_selection import cross_val_score
import os     
os.environ["PATH"] += os.pathsep + 'C:/Users/Thomas/Anaconda3/Library/bin/graphviz'

In [28]:
df_1 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_1/btcFeature.csv')
df_2 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_2/btcFeature.csv')
df_3 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_3/btcFeature.csv')
df_4 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_4/btcFeature.csv')

In [29]:
df_1.head(5)

Unnamed: 0      Change  NoOfTweets         Price  Sentiment   TimeStamp  \
0           0  -16.361552        5467  10895.972636   0.129824  1517006461   
1           0  160.020423        5126  11087.754289   0.164874  1517010061   
2           0   15.984359        4988  11190.677842   0.179189  1517013662   
3           0   17.695245        4938  11054.557901   0.164394  1517017261   
4           0  238.671977        4657  11146.846681   0.147747  1517020862   

          Volume  
0  101879.724252  
1  102390.922041  
2  103844.936107  
3  102671.806232  
4  100960.453183

In [30]:
dt = tree.DecisionTreeRegressor()
rf = RandomForestRegressor()

X = df_1['Sentiment']
Y = df_1['Change']

X = X.values.reshape(len(X), 1)
Y = Y.values.reshape(len(Y), 1)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=5)

dt.fit(X_train, Y_train)
rf.fit(X_train, Y_train)

C:\Users\Thomas\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  del sys.path[0]


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [31]:
score = cross_val_score(dt, X_test, Y_test)
dt_score = dt.score(X_test, Y_test)
rf_score = rf.score(X_test, Y_test)

print(score)
print(dt_score)
print(rf_score)

[-0.68307538 -1.76066372 -0.66452328]
-0.864494822711
-0.377337625796


In [32]:
dot_data = tree.export_graphviz(dt, out_file=None, 
                         feature_names=['Sentiment'],  
                         filled=True, rounded=False,  ) 
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_png('bit_tree.png')
graph.write_svg("bit_tree.svg")

True

In [33]:
dt = tree.DecisionTreeRegressor()
rf = RandomForestRegressor()

X = df_2['Sentiment']
Y = df_2['Change']

X = X.values.reshape(len(X), 1)
Y = Y.values.reshape(len(Y), 1)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=5)

dt.fit(X_train, Y_train)
rf.fit(X_train, Y_train)

C:\Users\Thomas\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  del sys.path[0]


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [34]:
score = cross_val_score(dt, X_test, Y_test)
dt_score = dt.score(X_test, Y_test)
rf_score = rf.score(X_test, Y_test)

print(score)
print(dt_score)
print(rf_score)

[-1.53026866 -0.88740762 -0.69518836]
-1.95643516338
-1.04032562012


In [35]:
dt = tree.DecisionTreeRegressor()
rf = RandomForestRegressor()

X = df_3['Sentiment']
Y = df_3['Change']

X = X.values.reshape(len(X), 1)
Y = Y.values.reshape(len(Y), 1)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=5)

dt.fit(X_train, Y_train)
rf.fit(X_train, Y_train)

C:\Users\Thomas\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  del sys.path[0]


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [36]:
score = cross_val_score(dt, X_test, Y_test)
dt_score = dt.score(X_test, Y_test)
rf_score = rf.score(X_test, Y_test)

print(score)
print(dt_score)
print(rf_score)

[-1.04171791 -1.22528273 -1.64830575]
-0.865444823016
-0.473944476973


In [37]:
dt = tree.DecisionTreeRegressor()
rf = RandomForestRegressor()

X = df_4['Sentiment']
Y = df_4['Change']

X = X.values.reshape(len(X), 1)
Y = Y.values.reshape(len(Y), 1)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=5)

dt.fit(X_train, Y_train)
rf.fit(X_train, Y_train)

C:\Users\Thomas\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  del sys.path[0]


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [38]:
print(score)
print(dt_score)
print(rf_score)

[-1.04171791 -1.22528273 -1.64830575]
-0.865444823016
-0.473944476973
