In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import preprocessing
from sklearn import utils
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_classification
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.model_selection import cross_val_score
import os     
os.environ["PATH"] += os.pathsep + 'C:/Users/Thomas/Anaconda3/Library/bin/graphviz'

In [2]:
df_1 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_1/ltcFeature.csv')
df_2 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_2/ltcFeature.csv')
df_3 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_3/ltcFeature.csv')
df_4 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_4/ltcFeature.csv')

In [3]:
df_1.head(5)

Unnamed: 0    Change  NoOfTweets       Price  Sentiment   TimeStamp  \
0           0 -0.232731         593  174.303061   0.155611  1517006461   
1           0  1.448909         454  176.100646   0.281581  1517010061   
2           0  0.539218         372  177.181654   0.218300  1517013662   
3           0  0.116144         342  175.854889   0.243829  1517017261   
4           0  2.127979         328  176.710563   0.224281  1517020862   

          Volume  
0  205541.904033  
1  204797.709286  
2  207919.066042  
3  208137.309780  
4  205240.060466

In [4]:
dt = tree.DecisionTreeRegressor()
rf = RandomForestRegressor()

X = df_1['Sentiment']
Y = df_1['Change']

X = X.values.reshape(len(X), 1)
Y = Y.values.reshape(len(Y), 1)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=5)

dt.fit(X_train, Y_train)
rf.fit(X_train, Y_train)

C:\Users\Thomas\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  del sys.path[0]


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [5]:
score = cross_val_score(dt, X_test, Y_test)
dt_score = dt.score(X_test, Y_test)
rf_score = rf.score(X_test, Y_test)

print(score)
print(dt_score)
print(rf_score)

[-0.21367985 -0.38942087 -0.60656554]
-0.692393375861
-0.380360634237


In [6]:
dt = tree.DecisionTreeRegressor()
rf = RandomForestRegressor()

X = df_2['Sentiment']
Y = df_2['Change']

X = X.values.reshape(len(X), 1)
Y = Y.values.reshape(len(Y), 1)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=5)

dt.fit(X_train, Y_train)
rf.fit(X_train, Y_train)

C:\Users\Thomas\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  del sys.path[0]


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [7]:
score = cross_val_score(dt, X_test, Y_test)
dt_score = dt.score(X_test, Y_test)
rf_score = rf.score(X_test, Y_test)

print(score)
print(dt_score)
print(rf_score)

[-0.13478902 -2.9947047  -0.84926438]
-2.16806125894
-0.923183345339


In [8]:
dt = tree.DecisionTreeRegressor()
rf = RandomForestRegressor()

X = df_3['Sentiment']
Y = df_3['Change']

X = X.values.reshape(len(X), 1)
Y = Y.values.reshape(len(Y), 1)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=5)

dt.fit(X_train, Y_train)
rf.fit(X_train, Y_train)

C:\Users\Thomas\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  del sys.path[0]


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [9]:
score = cross_val_score(dt, X_test, Y_test)
dt_score = dt.score(X_test, Y_test)
rf_score = rf.score(X_test, Y_test)

print(score)
print(dt_score)
print(rf_score)

[-0.55090899 -1.78118744 -1.25089408]
-0.995503214547
-0.323351079033


In [10]:
dt = tree.DecisionTreeRegressor()
rf = RandomForestRegressor()

X = df_4['Sentiment']
Y = df_4['Change']

X = X.values.reshape(len(X), 1)
Y = Y.values.reshape(len(Y), 1)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=5)

dt.fit(X_train, Y_train)
rf.fit(X_train, Y_train)

C:\Users\Thomas\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  del sys.path[0]


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [11]:
print(score)
print(dt_score)
print(rf_score)

[-0.55090899 -1.78118744 -1.25089408]
-0.995503214547
-0.323351079033
