In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import preprocessing
from sklearn import utils
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.model_selection import cross_val_score
import os     
import pydotplus
os.environ["PATH"] += os.pathsep + 'C:/Users/Thomas/Anaconda3/Library/bin/graphviz'

In [13]:
df_1 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_1/btcFeature.csv')
df_2 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_2/btcFeature.csv')
df_3 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_3/btcFeature.csv')
df_4 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_4/btcFeature.csv')

In [14]:
df_1.head(5)

Unnamed: 0      Change  NoOfTweets         Price  Sentiment   TimeStamp  \
0           0  -16.361552        5467  10895.972636   0.129824  1517006461   
1           0  160.020423        5126  11087.754289   0.164874  1517010061   
2           0   15.984359        4988  11190.677842   0.179189  1517013662   
3           0   17.695245        4938  11054.557901   0.164394  1517017261   
4           0  238.671977        4657  11146.846681   0.147747  1517020862   

          Volume  
0  101879.724252  
1  102390.922041  
2  103844.936107  
3  102671.806232  
4  100960.453183

In [15]:
shift = -1
random_state = 0
df_1.Change = df_1.Change.shift(shift)
df_1 = df_1.dropna()

In [16]:
average = 0.13 #0.145739 

df_1.Change = df_1.Change.astype(str)
df_1.Sentiment = df_1.Sentiment.astype(str)
for index, row in df_1.iterrows():
    if float(row['Change']) < 0.0:
        df_1.set_value(index,'Change', "Buy")
    else:
        df_1.set_value(index, 'Change', "Sell")
    if float(row['Sentiment']) <= average:
        df_1.set_value(index,'Sentiment', 1)
    else:
        df_1.set_value(index, 'Sentiment', -1)

df_2.Change = df_2.Change.astype(str)
df_2.Sentiment = df_2.Sentiment.astype(str)
for index, row in df_2.iterrows():
    if float(row['Change']) < 0.0:
        df_2.set_value(index,'Change', "Buy")
    else:
        df_2.set_value(index, 'Change', "Sell")
    if float(row['Sentiment']) <= average:
        df_2.set_value(index,'Sentiment', 1)
    else:
        df_2.set_value(index, 'Sentiment', -1)

In [17]:
clf = RandomForestClassifier(max_leaf_nodes=2, min_samples_leaf=50, max_depth=150)
dt = DecisionTreeClassifier(max_leaf_nodes=2, min_samples_leaf=50, max_depth=150)

X = df_1['Sentiment']
Y = df_1['Change']

X = X.values.reshape(len(X), 1)
Y = Y.values.reshape(len(Y), 1)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=0)

clf.fit(X_train, Y_train.ravel())
dt.fit(X_train, Y_train.ravel())

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=150,
            max_features=None, max_leaf_nodes=2, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=50,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [18]:
dt_cross_score = cross_val_score(dt, X_test, Y_test)
dt_score = dt.score(X_test, Y_test)

clf_cross_score = cross_val_score(clf, X_test, Y_test)
clf_score = clf.score(X_test, Y_test)

print(dt_cross_score)
print(dt_score)

print(clf_cross_score)
print(clf_score)

[ 0.5212766   0.5212766   0.51612903]
0.501779359431
[ 0.5212766   0.5212766   0.51612903]
0.501779359431


C:\Users\Thomas\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Thomas\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Thomas\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


In [19]:
clf.estimators_

[DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=150,
             max_features='auto', max_leaf_nodes=2,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=50, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=2062795497, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=150,
             max_features='auto', max_leaf_nodes=2,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=50, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=75921482, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=150,
             max_features='auto', max_leaf_nodes=2,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=50, min_samples_split=2,
             min_weight_fracti

In [20]:
dot_data = tree.export_graphviz(dt, out_file=None, 
                         feature_names=['Sentiment'],  
                         filled=True, rounded=False,  ) 
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_png('bit_tree.png')
graph.write_svg("bit_tree.svg")

True

In [21]:
clf = RandomForestClassifier()
dt = DecisionTreeClassifier(random_state=0)

X = df_2['Sentiment']
Y = df_2['Change']

X = X.values.reshape(len(X), 1)
Y = Y.values.reshape(len(Y), 1)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=0)

clf.fit(X_train, Y_train.ravel())
dt.fit(X_train, Y_train.ravel())

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [22]:
dt_cross_score = cross_val_score(dt, X_test, Y_test)
dt_score = dt.score(X_test, Y_test)

clf_cross_score = cross_val_score(clf, X_test, Y_test)
clf_score = clf.score(X_test, Y_test)

print(dt_cross_score)
print(dt_score)

print(clf_cross_score)
print(clf_score)

[ 0.54347826  0.46153846  0.52222222]
0.472527472527
[ 0.52173913  0.46153846  0.57777778]
0.479853479853


C:\Users\Thomas\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Thomas\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Thomas\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
