In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import preprocessing
from sklearn import utils
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_classification
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.model_selection import cross_val_score
import os     
os.environ["PATH"] += os.pathsep + 'C:/Users/Thomas/Anaconda3/Library/bin/graphviz'

In [2]:
df_1 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_1/ethFeature.csv')
df_2 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_2/ethFeature.csv')
df_3 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_3/ethFeature.csv')
df_4 = pd.read_csv('C:/Users/Thomas/Desktop/Bitcoin_Data/Version_4/ethFeature.csv')

In [3]:
df_1.head(5)

Unnamed: 0     Change  NoOfTweets        Price  Sentiment   TimeStamp  \
0           0  -1.862293          20  1038.782226  -0.110730  1517006461   
1           0   2.830701          19  1041.819050  -0.180437  1517010061   
2           0   3.437149          30  1058.019947  -0.230363  1517013662   
3           0  -2.754217          24  1046.343325  -0.100825  1517017261   
4           0  16.126054          22  1052.391492  -0.219436  1517020862   

          Volume  
0  266436.648954  
1  267513.591597  
2  269431.766453  
3  267752.618866  
4  267965.396091

In [4]:
dt = tree.DecisionTreeRegressor()
rf = RandomForestRegressor()

X = df_1['Sentiment']
Y = df_1['Change']

X = X.values.reshape(len(X), 1)
Y = Y.values.reshape(len(Y), 1)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=5)

dt.fit(X_train, Y_train)
rf.fit(X_train, Y_train)

C:\Users\Thomas\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  del sys.path[0]


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [5]:
score = cross_val_score(dt, X_test, Y_test)
dt_score = dt.score(X_test, Y_test)
rf_score = rf.score(X_test, Y_test)

print(score)
print(dt_score)
print(rf_score)

[-0.52152731 -1.84598478 -1.44742823]
-1.62797071318
-0.988762879146


In [6]:
dt = tree.DecisionTreeRegressor()
rf = RandomForestRegressor()

X = df_2['Sentiment']
Y = df_2['Change']

X = X.values.reshape(len(X), 1)
Y = Y.values.reshape(len(Y), 1)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=5)

dt.fit(X_train, Y_train)
rf.fit(X_train, Y_train)

C:\Users\Thomas\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  del sys.path[0]


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [7]:
score = cross_val_score(dt, X_test, Y_test)
dt_score = dt.score(X_test, Y_test)
rf_score = rf.score(X_test, Y_test)

print(score)
print(dt_score)
print(rf_score)

[-1.44857596 -0.35435895 -0.96735007]
-0.316362639222
-0.278208981195


In [8]:
dt = tree.DecisionTreeRegressor()
rf = RandomForestRegressor()

X = df_3['Sentiment']
Y = df_3['Change']

X = X.values.reshape(len(X), 1)
Y = Y.values.reshape(len(Y), 1)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=5)

dt.fit(X_train, Y_train)
rf.fit(X_train, Y_train)

C:\Users\Thomas\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  del sys.path[0]


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [9]:
score = cross_val_score(dt, X_test, Y_test)
dt_score = dt.score(X_test, Y_test)
rf_score = rf.score(X_test, Y_test)

print(score)
print(dt_score)
print(rf_score)

[-1.25749691 -0.18144831 -3.53075916]
-1.32305492346
-0.61152842349


In [10]:
dt = tree.DecisionTreeRegressor()
rf = RandomForestRegressor()

X = df_4['Sentiment']
Y = df_4['Change']

X = X.values.reshape(len(X), 1)
Y = Y.values.reshape(len(Y), 1)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=5)

dt.fit(X_train, Y_train)
rf.fit(X_train, Y_train)

C:\Users\Thomas\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  del sys.path[0]


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [11]:
print(score)
print(dt_score)
print(rf_score)

[-1.25749691 -0.18144831 -3.53075916]
-1.32305492346
-0.61152842349
